### ISSUE TITLE
Success Criterion 3.3.7 - Redundant Entry - Level AA

### ISSUE THREAD

**Issue by JJdeGroot** [w3c/matf#59] opened 2024-07-18 06:44 UTC
WCAG2ICT guidance: https://www.w3.org/TR/wcag2ict-22/#redundant-entry

Share your thoughts for applying to mobile apps as a comment below.

**Comment by julianmka** [comment] 2024-08-27 00:39
@JJdeGroot, this issue seems to be a duplicate of #46. Could we close this one and keep discussion in #46?

**Comment by julianmka** [comment] 2024-08-28 14:49
Closing as this issue duplicates #46.

**Closed by julianmka** 2024-08-28 14:49 UTC
Labels: duplicate, small-variation
